### ISSUE TITLE
Suggestion: add clang-format file to the project

### ISSUE THREAD

**Issue by mapron** [kleinschrader/kleinsHTTP#10]
.. and format files according to it.

In my company I get so used to auto formatting that reading lines like

```
void kleins::httpServer::on(const std::string& method,const std::string& uri, const std::function<void(httpParser*)> callback)
```
or
```
    std::basic_ifstream<char> instream(path, std::ios::binary);
    instream.read(&filedata[0],filesize);
```
gives me almost physical pain.
(if not clear: inconsistent spaces, line breaks, et cetera)

**Comment by kleinschrader** [comment]
Hey @mapron , thanks for your feedback.
I never really considered readability.

Are the changes in #11 sufficient or do you have anymore suggestions?

**Comment by mapron** [comment]
Yeah, you can close it.

**Comment by mapron** [comment]
@kleinschrader , it's not my project, but... 
https://github.com/kleinschrader/kleinsHTTP/commits/main
" chore(formating): Implemented suggestions of @mapron "
it's a pretty BAD commit message to have in the history. It's fine to have them in branches, but I usually rewrite (interactive rebase) such messages.

1. referencing to some user in MR in the history is useless
2. changes itself has more than message describes.

(sorry for poor words choice, I hope 'useless' is not offending!)

Again, that's all is nitpicking based how in MY company working with Git done (and how I try to do it for my own projects on Github).

**Comment by kleinschrader** [comment]
No problem at all. I actually really appreciate your feedback and will strife to do better.
Thank you again for everything :smile:
